### ISSUE TITLE
PhoneGap Build Service - Unable to compile with PayPal plugin v3.2.2 via NPM

### ISSUE THREAD

**Issue by bigz90210** [phonegap/phonegap-app-desktop#642]
I'm getting a Build JAVAC compilation error (from the log) of Package Import not found for PayPal Payments when using NPM. But it does work via PGB v3.1.2 (config.xml: [plugin name="com.paypal.cordova.mobilesdk" source="pgb" spec="3.1.2"/]).

Error message from Build log:
/project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:20: error: package com.paypal.android.sdk.payments does not exist
import com.paypal.android.sdk.payments.*;

config.xml
[plugin name="com.paypal.cordova.mobilesdk" source="npm" spec="3.2.2"/]

Build log messages:
Fetching plugin "com.paypal.cordova.mobilesdk@3.2.2" via npm
Installing "com.paypal.cordova.mobilesdk" at "3.2.2" for android
Fetching plugin "card.io.cordova.mobilesdk" via npm
Installing "card.io.cordova.mobilesdk" at "2.0.2" for android

Did anyone run into this issue?

**Comment by hermwong** [comment]
This is a PhoneGap Build issue and should be asked on the [PhoneGap Build Forums](https://forums.adobe.com/community/phonegap/build).
